/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw1;

import static spark.Spark.get;
import static spark.Spark.post;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

//import org.apache.logging.log4j.core.Logger;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import spark.ModelAndView;
import spark.template.mustache.MustacheTemplateEngine;

public class App {
    /**
     * 
     * @param sayiUzayi sayi arrayi bu sayilar gruplanacak
     * @param tane sayiUzayina eklenecek yeni sayilarin sayisi
     * @param kucuk gruplandirmada kullanilacak kucuk sayi
     * @param buyuk gruplandirmada kullanilacak buyuk sayi
     */

    public String getGreeting(){
        return "Hello World";
    }


    public static int[] groupByTwoInt(ArrayList<Integer> sayiUzayi,int tane,int kucuk,int buyuk) {
        ArrayList<Integer> grup=new ArrayList<Integer>();
        
        if(kucuk>buyuk){
            System.out.println("kucuk sayi buyuk sayidan buyuk olamaz");
            return null;
        }

        if(sayiUzayi.size()==0){
            System.out.println("sayiUzayi bos olamaz");
            return null;
        }
        
        if(tane<0){
            System.out.println("eklenecek sayi negatif olamaz");
            return null;
        }
        


        for(int i=0;i<tane-1;i++){
            sayiUzayi.add((int)(Math.random()*100));
        }
        
        for(int sayi : sayiUzayi){
            
            if(sayi>kucuk && sayi<buyuk){
                grup.add(sayi);
            }

        }

        int[] arr=new int[grup.size()];
        grup.sort(null);
        
        for(int i=0;i<grup.size();i++)
            arr[i]=grup.get(i);
        
            

        return arr;
    }

    public static void main(String[] args) {
        Logger logger = LogManager.getLogger(App.class);
        logger.error("!!!error occurred!!!");

        System.out.println(new App().getGreeting());

        get("/", (req,res) -> "Hello World!!!!!");
        post("/compute", (req,res)-> {

            String input1=req.queryParams("array");
            input1=input1.replaceAll("[;\r\n]+", ",");
            String[] strArr=input1.split(",");

            ArrayList<Integer> arr=new ArrayList<Integer>(strArr.length);

            for(int i=0;i<strArr.length;i++){
                arr.add(Integer.parseInt(strArr[i]));     
            }

            String input2=req.queryParams("tane").replaceAll("\\s", "");
            int tane=Integer.parseInt(input2);

            String input3=req.queryParams("kucuk_sayi").replaceAll("\\s", "");
            int kucuk=Integer.parseInt(input3);

            String input4=req.queryParams("buyuk_sayi").replaceAll("\\s", "");
            int buyuk=Integer.parseInt(input4);

            int[] sonuc=groupByTwoInt(arr, tane, kucuk, buyuk);
            
            String result="{";
            for(int a:sonuc)
                result=result+" "+a;
            result=result+" }";

            Map<String,String> map=new HashMap<String,String>();
            map.put("result",result);

            return new ModelAndView(map, "compute.mustache");
            
        }, new MustacheTemplateEngine());

        get("compute",
            (rq,rs)->{

                Map<String,String> map=new HashMap<String,String>();
                map.put("result","not computed yet!");
                return new ModelAndView(map,"compute.mustache");

            },

            new MustacheTemplateEngine()

        );
    }
}
