/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testFound(){
        ArrayList<Integer> array=new ArrayList<Integer>(Arrays.asList(12,23,75,25,18,78));
        int tane=2;
        int kucuk=10;
        int buyuk=52;
        assertNotNull(App.groupByTwoInt(array,tane,kucuk,buyuk));

    }
    
    @Test
    public void buyukKucukKontrol(){
        ArrayList<Integer> array=new ArrayList<Integer>(Arrays.asList(12,23,75,25,18,78));
        int tane=2;
        int kucuk=10;
        int buyuk=2;
        assertNull(App.groupByTwoInt(array,tane,kucuk,buyuk));
    }
    
    @Test
    public void arrayKontrol(){
        ArrayList<Integer> array=new ArrayList<Integer>();
        int tane=2;
        int kucuk=10;
        int buyuk=52;
        assertNull(App.groupByTwoInt(array,tane,kucuk,buyuk));
    }

    @Test
    public void eklenecekSayiKontrol(){
        ArrayList<Integer> array=new ArrayList<Integer>(Arrays.asList(12,23,75,25,18,78));
        int tane=-22;
        int kucuk=10;
        int buyuk=52;
        assertNull(App.groupByTwoInt(array,tane,kucuk,buyuk));
    }

    @Test
    public void sonucKontrol(){
        ArrayList<Integer> array=new ArrayList<Integer>(Arrays.asList(12,23,75,25,18,78));
        int tane=0;
        int kucuk=10;
        int buyuk=52;
        int[] kont={12,18,23,25};
        assertArrayEquals(App.groupByTwoInt(array,tane,kucuk,buyuk), kont);
    }

    
    

}
